### ISSUE TITLE
ym3438 emu copyright

### ISSUE THREAD

**Issue by nukeykt** [fedex81/helios#1]
Hi,
Nice to see you're using my core for ym3438, but i wonder why did you remove original copyright from it. It is derived work from my original implementation, so it should not be removed

**Comment by fedex81** [comment]
Apologies, it has been somehow stripped from the files, I will reinstate it.

**Comment by fedex81** [comment]
Fixed by 3e976efd1bb9447d304bfc9427368ada3b9162cb

**Comment by nukeykt** [comment]
Thanks 😃

**Comment by fedex81** [comment]
Thanks for your great emu ;)
