### ISSUE TITLE
Cycle synchronization hang

### ISSUE THREAD

**Issue by krlvm** [fedex81/helios#3]
Hello, I'm experiencing problems with hanging of the game cycle thread: the thread is paused with a regularity of a couple of seconds (CPU utilization grows on resume and becomes 0 on freeze) making emulator impossible to use.

![vm](https://user-images.githubusercontent.com/51774833/87192860-07699e00-c300-11ea-8ee4-a60384acfd5d.png)

I figured out the cause of the problem is a bottleneck in [the cycle synchronization algorithm](https://github.com/fedex81/helios/blob/master/src/main/java/omegadrive/system/BaseSystem.java#L294): the [`park`](https://github.com/fedex81/helios/blob/master/src/main/java/omegadrive/util/Util.java#L75) method of [`Util`](https://github.com/fedex81/helios/blob/master/src/main/java/omegadrive/util/Util.java) class. The thread should be suspended for a 5-6 milliseconds, but it's actually led to a significant freeze and takes a half of a second at least.

I rewrote the parking algorithm and game runs smoothly without any freezes, but I have doubts about thread-safety:
```java
public static void park(long intervalNs) {
    long resume = System.nanoTime() + intervalNs;
    while(System.nanoTime() < resume) {
    }
}
```
Can it fix the rendering freezes, or this problem is related to my CPU clock speed?

**Comment by fedex81** [comment]
Interesting, there is something dodgy going on with park; I'll have a look on my windows box when I have some time.

> I rewrote the parking algorithm and game runs smoothly without any freezes, but I have complains about thread-safety:
What kind of complaints are you getting?

**Comment by krlvm** [comment]
> What kind of complaints are you getting?
I confused words, wanted to say doubts instead.\
IDK, all is working well, but I think there was a reason to park the thread.

**Comment by krlvm** [comment]
I uploaded [demonstration of the problem](https://github.com/fedex81/helios/files/4907223/comparasion.zip), pay attention to the sound freezing and the in-game time counter.\
BTW, there's PSG sound distortion (notable on player jump in Sonic 3), may it be a Windows-specific issue?

**Comment by fedex81** [comment]
> I rewrote the parking algorithm and game runs smoothly without any freezes, but I have doubts about thread-safety:
> 


> ```java
> public static void park(long intervalNs) {
>     long resume = System.nanoTime() + intervalNs;
>     while(System.nanoTime() < resume) {
>     }
> }
> ```

This looks fine (busy-waiting), it is obviously keeping your cpu very busy; you can try the one below which is a bit nicer on the CPU:
```java
public static void park(long intervalNs) {
     long resume = System.nanoTime() + intervalNs;
     while(System.nanoTime() < resume) {
        Thread.yield();
     }
 }
```

**Comment by krlvm** [comment]
Good solution, saves ~2-3% of CPU compared to the previous version, thanks. I think it should be included in the main branch.
