### ISSUE TITLE
PSG vs FM desync

### ISSUE THREAD

**Issue by krlvm** [fedex81/helios#4]
There's a PSG sound distortion with Mega Drive emulator (it actually sounds Sega Master System-ish), it very noticeable on player jump in Sonic games, for example. I also noticed it slightly out of sync with FM synthesizer.\
I tried to port SN76489 implementation from some other emulators written in C/C++, but this gave no effect. Experiments with mixer from SoundUtil did not give result too.

**Comment by krlvm** [comment]
I see you've fixed this issue.\
Thank you!

**Comment by krlvm** [comment]
@fedex81 PSG sounds clean and nice after the fix, but now it's completely desynced with FM synthesizer.

**Comment by fedex81** [comment]
Not really happy with my audio layer, will I find time to improve it? we shall see.

A few issues:
- fm is buffered while psg is not, they should use the same buffer to avoid desync
- win10: I noticed the fm buffer (ie. delay) is all over the place; it can get to 300ms 
- would be good to explore something like xtAudio: https://sjoerdvankreel.github.io/xt-audio/
- sync emulation to audio

**Comment by fedex81** [comment]
> win10: I noticed the fm buffer (ie. delay) is all over the place; it can get to 300ms

This should be fixed with release 20.1207 - 80ac3f4349d419a08f3d2e052344d01c7065997
